version: "2.4"
services:
  frontend:
    build: ./frontend
    networks:
      - backbone
    ports:
      - 443:443
    depends_on:
      - backend
  backend:
    build: ./backend
    networks:
      - backbone
    volumes:
      - databasevol:/database
networks:
  backbone:
    driver: bridge
volumes:
  databasevol: