version: "2.4"
services:
  frontend:
    image: livepollregistry.azurecr.io/livepoll/frontend:latest
    networks:
      - backbone
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    image: livepollregistry.azurecr.io/livepoll/backend:latest
    networks:
      - backbone
    volumes:
      - databasevol:/database
networks:
  backbone:
    driver: bridge
volumes:
  databasevol: